#pragma once

enum EventTypes
{
    EXCEPTION_DIVIDE_ERROR,
    EXCEPTION_DEBUG_BREAKPOINT,
    EXCEPTION_NMI_INTERRUPT,
    EXCEPTION_BREAKPOINT,
    EXCEPTION_OVERFLOW,
    EXCEPTION_BOUND_RANGE_EXCEEDED,
    EXCEPTION_UNDEFINED_OPCODE,
    EXCEPTION_NO_MATH_COPROCESSOR,
    EXCEPTION_DOUBLE_FAULT_INTERRUPT,
    EXCEPTION_RESERVED0,
    EXCEPTION_INVALID_TASK_SEGMENT_SELECTOR,
    EXCEPTION_SEGMENT_NOT_PRESENT_INTERRUPT,
    EXCEPTION_STACK_SEGMENT_FAULT,
    EXCEPTION_GENERAL_PROTECTION_FAULT,
    EXCEPTION_PAGE_FAULT,
    EXCEPTION_RESERVED1,
    EXCEPTION_MATH_FAULT,
    EXCEPTION_ALIGNMENT_CHECK_INTERRUPT,
    EXCEPTION_MACHINE_CHECK,
    EXCEPTION_SIMD_FLOATING_POINT_NUMERIC_ERROR,
    EXCEPTION_VIRTUAL_EXCEPTION,
    EXCEPTION_CONTROL_POINT_EXCEPTION,
    EXCEPTION_RESERVED3,
    EXCEPTION_RESERVED4,
    EXCEPTION_RESERVED5,
    EXCEPTION_RESERVED6,
    EXCEPTION_RESERVED7,
    EXCEPTION_RESERVED8,
    EXCEPTION_RESERVED9,
    EXCEPTION_RESERVED10,
    EXCEPTION_RESERVED11,
    EXCEPTION_RESERVED12,
};

enum InterruptVectors
{
    INTERRUPT_TYPE_EXTERNAL_INTERRUPT,
    INTERRUPT_TYPE_RESERVED,
    INTERRUPT_TYPE_NMI,
    INTERRUPT_TYPE_HARDWARE_EXCEPTION,
    INTERRUPT_TYPE_SOFTWARE_INTERRUPT,
    INTERRUPT_TYPE_PRIVILEGED_SOFTWARE_INTERRUPT,
    INTERRUPT_TYPE_SOFTWARE_EXCEPTION,
    INTERRUPT_TYPE_OTHER_EVENT,
};

namespace VmExitHandlers
{
    uint16_t VmNmiHandler(PGUEST_STATE pGuestState);
    uint16_t VmExternalInterrupt(PGUEST_STATE pGuestState);
    uint16_t VmCommunicationHandler(PGUEST_STATE pGuestState);
	uint16_t VmHandleCpuid(PGUEST_STATE pGuestState);
	uint16_t VmHandleRdmsr(PGUEST_STATE pGuestState);
	uint16_t VmHandleWrmsr(PGUEST_STATE pGuestState);
	uint16_t VmHandleXsetbv(PGUEST_STATE pGuestState);
	uint16_t VmHandleControlRegister(PGUEST_STATE pGuestState);
    uint16_t VmHandleGenericVmx(PGUEST_STATE pGuestState);
    uint16_t VmHandleEptViolation(PGUEST_STATE pGuestState);

	void VmInjectEvent(uint16_t InterruptType, uint16_t EventType);
}